### ISSUE TITLE
questions about the texture pack section

### ISSUE THREAD

**Issue by Zarkness2** [ItsFlicker/FlTools#1]
What versions is the plugin compatible with? add support from 1.12 onwards.
If it is possible to add that the user can put or remove a texture pack from a list of texture packs that were put in the config also add some placeholder that could be %FlTools_<texturepack>% and return true or false on whether you have the texture pack that you put in the config more than anything to use it as a condition in menus and to put if you want one of those texture pack is mandatory also add that each texture pack has its option of onloaded, ondeclined, onaccepted and onfaileddownload and add if possible add an action for when you remove the texture pack and add compatibility with itemsadder and oraxen.

**Comment by Zarkness2** [comment]
@ItsFlicker

**Comment by Zarkness2** [comment]
@ItsFlicker of what I said will you add only some things or will you add everything? preferably I would like you to add everything, but it depends on whether it is possible or not.

**Comment by ItsFlicker** [comment]
A player can only set a resource pack at a time without a mod, so `onRemoved` is called when putting another pack.

ItemsAdder: 
```yaml
- id: 'itemsadder'
  ...
```
Oraxen:
```yaml
- id: 'oraxen'
  ...
```

send: `/fltools sendResourcePack <player> <id>`

Please test 1.0.2 if its new features work.
You need to regenerate config.yml.

**Comment by Zarkness2** [comment]
ok, now I'll try it, but how would the user remove the texture pack he currently has, in order to get another one?

**Comment by Zarkness2** [comment]
one thing and what versions does the plugin support?

**Comment by Zarkness2** [comment]
by the way add the /fltools reload command, otherwise every time I edit the config I have to restart the server.

**Comment by ItsFlicker** [comment]
> one thing and what versions does the plugin support?

flmisc: 1.18+
other functions: 1.8-1.19

**Comment by Zarkness2** [comment]
ok, so the texture pack is supported from 1.8 onwards

**Comment by ItsFlicker** [comment]
> ok, now I'll try it, but how would the user remove the texture pack he currently has, in order to get another one?

The only possible way to remove texture pack is to send an empty texture pack as vanilla client doesn't provide a method to remove texture packs

**Comment by ItsFlicker** [comment]
If you send another texture pack, the previous one will be covered

**Comment by ItsFlicker** [comment]
> by the way add the /fltools reload command, otherwise every time I edit the config I have to restart the server.

config will auto reload when saving config file

**Comment by Zarkness2** [comment]
> config will auto reload when saving config file



> > by the way add the /fltools reload command, otherwise every time I edit the config I have to restart the server.
> 
> config will auto reload when saving config file

okay, I thought there was a wayokay, I thought there was a way

**Comment by Zarkness2** [comment]
> > by the way add the /fltools reload command, otherwise every time I edit the config I have to restart the server.
> 
> config will auto reload when saving config file

if it has auto reload better, now I'll try it and I'll tell you, by the way how do I make one of those texture packs mandatory?

**Comment by ItsFlicker** [comment]
> > > by the way add the /fltools reload command, otherwise every time I edit the config I have to restart the server.
> > 
> > 
> > config will auto reload when saving config file
> 
> if it has auto reload better, now I'll try it and I'll tell you, by the way how do I make one of those texture packs mandatory?

perform the send command when player login or join, and set the texture pack's onDeclined to kick the player

**Comment by Zarkness2** [comment]
okay, thank you very much

**Comment by Zarkness2** [comment]
that's what I get when I enter the texture pack id which in this case I put test and when I hit enter it doesn't send me the texture pack.
https://paste.helpch.at/ojasadonad.rb

**Comment by ItsFlicker** [comment]
maybe @ConfigNode doesn't support companion object 
fixed in https://github.com/FlickerProjects/FlTools/actions/runs/2581821933

**Comment by Zarkness2** [comment]
these are all the errors I found in the plugin

these are the errors I get with the /fltools light command and what follows it
1. https://paste.helpch.at/igutipijay.sql
2. https://paste.helpch.at/vofenasiwu.sql
3. https://paste.helpch.at/dibarediqe.sql
4. https://paste.helpch.at/zejicuyaye.sql
5. https://paste.helpch.at/zaxopoyima.sql
6. https://paste.helpch.at/gosejoweji.sql

put a limit to the /fltools lore insert command since it throws you out when you put in line 90 any word and if you have the item it is throwing you out all the time until you are deleted.
https://paste.helpch.at/jigoxewano.md

error when putting the command /fltools lore pop 1 asa I put 1 asa because it does not explain what to put or how to use it.
https://paste.helpch.at/fohujamequ.rb

error when putting the command /fltools sendToast Zarkness CHALLENGE YELLOW_WOOL asdas and if I put it without the asdas it does not send the message and the same with the other sendtoast options.
https://paste.helpch.at/pezehibazi.rb

**Comment by Zarkness2** [comment]
one thing, how can I make them need a x permission to be able to use the texture pack?
once I reject a texture pack it doesn't let me put any other one, is that fixable from inside the server? I know I would have to exit and change the server resource pack option, but is there any way to change that without exiting the server?

**Comment by Zarkness2** [comment]
another thing is it normal that when the texture pack is downloading, the percentage is negative? and all the texture packs that I try reach 100% and I get that message.
![image](https://user-images.githubusercontent.com/48263644/176399617-e2cb1707-f9ac-4fa0-84dc-f71ac783d03a.png)

**Comment by ItsFlicker** [comment]
> another thing is it normal that when the texture pack is downloading, the percentage is negative? and all the texture packs that I try reach 100% and I get that message. ![image](https://user-images.githubusercontent.com/48263644/176399617-e2cb1707-f9ac-4fa0-84dc-f71ac783d03a.png)

This did not happen on my local server. What's your version?

**Comment by ItsFlicker** [comment]
> one thing, how can I make them need a x permission to be able to use the texture pack? once I reject a texture pack it doesn't let me put any other one, is that fixable from inside the server? I know I would have to exit and change the server resource pack option, but is there any way to change that without exiting the server?

permission support will be added in next version
it seemed that changing server resource pack option is impossible without exiting the server

**Comment by ItsFlicker** [comment]
> these are all the errors I found in the plugin
> 
> these are the errors I get with the /fltools light command and what follows it
> 
> 1. https://paste.helpch.at/igutipijay.sql
> 2. https://paste.helpch.at/vofenasiwu.sql
> 3. https://paste.helpch.at/dibarediqe.sql
> 4. https://paste.helpch.at/zejicuyaye.sql
> 5. https://paste.helpch.at/zaxopoyima.sql
> 6. https://paste.helpch.at/gosejoweji.sql
> 
> put a limit to the /fltools lore insert command since it throws you out when you put in line 90 any word and if you have the item it is throwing you out all the time until you are deleted. https://paste.helpch.at/jigoxewano.md
> 
> error when putting the command /fltools lore pop 1 asa I put 1 asa because it does not explain what to put or how to use it. https://paste.helpch.at/fohujamequ.rb
> 
> error when putting the command /fltools sendToast Zarkness CHALLENGE YELLOW_WOOL asdas and if I put it without the asdas it does not send the message and the same with the other sendtoast options. https://paste.helpch.at/pezehibazi.rb

toast and light is depend on TabooLib, waiting for fixing

pop [line]: Delete the specific line of lore

**Comment by Zarkness2** [comment]
> > another thing is it normal that when the texture pack is downloading, the percentage is negative? and all the texture packs that I try reach 100% and I get that message. ![image](https://user-images.githubusercontent.com/48263644/176399617-e2cb1707-f9ac-4fa0-84dc-f71ac783d03a.png)
> 
> This did not happen on my local server. What's your version?

in local I use fabric 1.18.2 and in the server 1.18.2 paper, although there should be no problem in using fabric 1.18.2 in local since in other servers when they ask me for texture pack if I download it.

**Comment by Zarkness2** [comment]
> > one thing, how can I make them need a x permission to be able to use the texture pack? once I reject a texture pack it doesn't let me put any other one, is that fixable from inside the server? I know I would have to exit and change the server resource pack option, but is there any way to change that without exiting the server?
> 
> permission support will be added in next version it seemed that changing server resource pack option is impossible without exiting the server

ok, so no problem, we will have to wait for the next version and we will have to tell the users that if they reject the texture pack to change that option.

**Comment by Zarkness2** [comment]
> toast and light is depend on TabooLib, waiting for fixing
> 
> pop [line]: Delete the specific line of lore

okay, I thought it was for something else

**Comment by ItsFlicker** [comment]
> ok, so no problem, we will have to wait for the next version and we will have to tell the users that if they reject the texture pack to change that option.

You can try to use permissions by menu

**Comment by Zarkness2** [comment]
> You can try to use permissions by menu

is what I had in mind but you can skip it by putting /fltools sendResourcePack its id name, because I want that you can also put the texture pack by the command if you don't want to go to the menu, otherwise I will have to create an alias for each texture pack and that way you will need

**Comment by Zarkness2** [comment]
> > > another thing is it normal that when the texture pack is downloading, the percentage is negative? and all the texture packs that I try reach 100% and I get that message. ![image](https://user-images.githubusercontent.com/48263644/176399617-e2cb1707-f9ac-4fa0-84dc-f71ac783d03a.png)
> > 
> > 
> > This did not happen on my local server. What's your version?
> 
> in local I use fabric 1.18.2 and in the server 1.18.2 paper, although there should be no problem in using fabric 1.18.2 in local since in other servers when they ask me for texture pack if I download it.

ok, now I download it well it was because I had put wrong the url I had put dl=0 instead of dl=1

**Comment by Zarkness2** [comment]
By the way, did you add the placeholders?

**Comment by Zarkness2** [comment]
another thing could you add support for this plugin https://polymart.org/resource/magic-cosmetics-20-off.2070 ?

**Comment by ItsFlicker** [comment]
> By the way, did you add the placeholders?

Yes, %fltools_rp_<id>% will return true or false

**Comment by Zarkness2** [comment]
okay, thank you very much

**Comment by Zarkness2** [comment]
Hi, one if a user accepts the texture pack and when they accept it gives them a permission if they leave the server the plugin removes that permission? @ItsFlicker

**Comment by ItsFlicker** [comment]
Well, I upgraded the command to `/ft rp <id> <player?>`
You can set a texture pack's permission now, if a player has it, he can use the command to get the texture pack
If a player has `fltools.command.rp.other`, he can send texture pack to other players

**Comment by ItsFlicker** [comment]
> Hi, one if a user accepts the texture pack and when they accept it gives them a permission if they leave the server the plugin removes that permission? @ItsFlicker

(v1.0.3)
Set onLoaded to give player permission, and set onRemoved to revoke player's permission

**Comment by Zarkness2** [comment]
ok, thank you very much, the truth is that whatever is asked of you if you think it's a good idea you do it pretty fast and well, I wish all the devs were like that.

One question, do you accept suggestions for future plugins you make?

**Comment by Zarkness2** [comment]
a question why don't you publish your plugins in spigotmc or mc-market?

**Comment by Zarkness2** [comment]
@ItsFlicker ?

**Comment by ItsFlicker** [comment]
> ok, thank you very much, the truth is that whatever is asked of you if you think it's a good idea you do it pretty fast and well, I wish all the devs were like that.
> 
> One question, do you accept suggestions for future plugins you make?

Of course. But I am going to senior high school, my updating will be slow

**Comment by ItsFlicker** [comment]
> a question why don't you publish your plugins in spigotmc or mc-market?

I will publish when plugins are stable

**Comment by Zarkness2** [comment]
> > ok, thank you very much, the truth is that whatever is asked of you if you think it's a good idea you do it pretty fast and well, I wish all the devs were like that.
> > One question, do you accept suggestions for future plugins you make?
> 
> Of course. But I am going to senior high school, my updating will be slow

I don't know if you agree with me but a slow update is better than no update at all.

**Comment by Zarkness2** [comment]
> > a question why don't you publish your plugins in spigotmc or mc-market?
> 
> I will publish when plugins are stable

okay, I thought you didn't want to post them on spigotmc or mc-market for some other reason.

**Comment by Zarkness2** [comment]
I am going to leave you some suggestions and if you decide to do any of them well and if not also

firts suggest:
suggestion would be a jetpack plugin that combines the mechanics of these 2 plugins.

It would have support for all armors so it could be any type of armor.

Multiple jetpacks and fuel by permission, customizable name and lore (you could create jetpacks that do not need fuel and if they are unbreakable or not).
Custom jetpack flight speed.

Different types of flight that would be: Flight type /fly that is the one that brings the fjetpacks and flight type realistic that is the one that uses the jetpack.

To be able to put in the config of each jetpack that gives you different effects.

Add a way that if you edit an existing jetpack and someone already has it, you can change it or give directly the new jetpack with the amount of fuel that had the previous one.
Add 2 types of boost per command and permission where you could set the boost level and the duration of the boost, the boosts would be speed boost and fuel durability boost.

Add support for SuperiorSkyblock, lands and worldguard plugins, in the superiorskyblock create a flag to put in the plugin so people can decide which roles on the island can use the jetpack on their island, (example of flags plugin https://github.com/Ynfuien/SuperiorSkyblockExtraFlags, wiki https://wiki.bg-software.com/superiorskyblock/overview/api) in the lands create a flag to be able to put in which zones or ranks can use it (wiki https://github.com/Angeschossen/LandsAPI).

Add the possibility to put particles or effects to each jetpack from the config and then each user could deactivate the default one and put the particles or effects they want (the effects could be created custom from a .yml).

idea of the particles and effects taken from the plugin: https://www.spigotmc.org/resources/trelytra-fully-customizable-lightweight-elytra-particle-effects-1-16-1-19.99860/
jetpacks plugins: https://www.spigotmc.org/resources/fjetpackreloaded.100816/
https://www.spigotmc.org/resources/jetpack-1-7-1-14.42781/


second suggest: (this suggestion if you don't understand it very well tell me and I will try to explain it further)
I don't know if you played hypixel skyblock and you know what is the canvas room, my idea is a plugin like that:

you would have a spray which you fill with dyes, if you left click on the item it would open a menu where you could choose the public maps that people made or that were put pre-made and another one for maps that you made.

then there will be an area that the staff selected as canvas room where people can make their own pictures on a huge canvas and with a command could transform the image that made that user on a map and could even decide whether to put in the previous menu the image you made.

clearly it would be good to have placeholders so you can use them in other places or as a condition for anything.

links that I was guided by:
https://hypixel-skyblock.fandom.com/wiki/Spray_Can
https://hypixel-skyblock.fandom.com/wiki/Canvas_Room
https://www.youtube.com/watch?v=5v33yhwPyLE
https://youtu.be/9cKLWZW2Vbk

**Comment by Zarkness2** [comment]
@ItsFlicker anything about plugins suggestions ask no problem and if you prefer to talk to me on discord this is my user tag `! Zarkness#0291`

**Comment by Zarkness2** [comment]
Another plugin suggestion would be a /shop plugin like shopgui+ with all that plugin has, trmenu style menu configuration system.

**Comment by Zarkness2** [comment]
@ItsFlicker

**Comment by ItsFlicker** [comment]
OK, thank you for your suggestions.
I will work on the first suggest firstly in this vacation.
The second suggest is a bit difficult for me, but I will try it.

**Comment by Zarkness2** [comment]
I'm surprised you accepted the 2 suggestions, not all devs would accept those suggestions if in the future you want more plugin suggestions let me know and I'll give you more. @ItsFlicker

**Comment by Zarkness2** [comment]
> OK, thank you for your suggestions. I will work on the first suggest firstly in this vacation. The second suggest is a bit difficult for me, but I will try it.

one question when will you start with the jetpack plugin? that is the first suggestion @ItsFlicker

**Comment by Zarkness2** [comment]
> > OK, thank you for your suggestions. I will work on the first suggest firstly in this vacation. The second suggest is a bit difficult for me, but I will try it.
> 
> one question when will you start with the jetpack plugin? that is the first suggestion @ItsFlicker

more than anything because the dev of the plugin fjetpacks that I had passed you does not do things very well and does them by halves and I prefer to use your plugins rather than those of a dev like him, besides that it took 2 months to add the flag for the superiorskyblock because he did not answer or put to do it and when he did it is not that he did it very well we say

**Comment by Zarkness2** [comment]
> OK, thank you for your suggestions. I will work on the first suggest firstly in this vacation. The second suggest is a bit difficult for me, but I will try it.

one thing i forgot to put in the jetpacks suggestion, an import from fjetpacks to your plugin

**Comment by Zarkness2** [comment]
Hi @ItsFlicker, could you fix that you can't download the latest version? and could you check discord when you can?

**Comment by Zarkness** [comment]
@ItsFlicker ?

**Comment by Zarkness2** [comment]
> I am going to leave you some suggestions and if you decide to do any of them well and if not also
> 
> firts suggest: suggestion would be a jetpack plugin that combines the mechanics of these 2 plugins.
> 
> It would have support for all armors so it could be any type of armor.
> 
> Multiple jetpacks and fuel by permission, customizable name and lore (you could create jetpacks that do not need fuel and if they are unbreakable or not). Custom jetpack flight speed.
> 
> Different types of flight that would be: Flight type /fly that is the one that brings the fjetpacks and flight type realistic that is the one that uses the jetpack.
> 
> To be able to put in the config of each jetpack that gives you different effects.
> 
> Add a way that if you edit an existing jetpack and someone already has it, you can change it or give directly the new jetpack with the amount of fuel that had the previous one. Add 2 types of boost per command and permission where you could set the boost level and the duration of the boost, the boosts would be speed boost and fuel durability boost.
> 
> Add support for SuperiorSkyblock, lands and worldguard plugins, in the superiorskyblock create a flag to put in the plugin so people can decide which roles on the island can use the jetpack on their island, (example of flags plugin https://github.com/Ynfuien/SuperiorSkyblockExtraFlags, wiki https://wiki.bg-software.com/superiorskyblock/overview/api) in the lands create a flag to be able to put in which zones or ranks can use it (wiki https://github.com/Angeschossen/LandsAPI).
> 
> Add the possibility to put particles or effects to each jetpack from the config and then each user could deactivate the default one and put the particles or effects they want (the effects could be created custom from a .yml).
> 
> idea of the particles and effects taken from the plugin: https://www.spigotmc.org/resources/trelytra-fully-customizable-lightweight-elytra-particle-effects-1-16-1-19.99860/ jetpacks plugins: https://www.spigotmc.org/resources/fjetpackreloaded.100816/ https://www.spigotmc.org/resources/jetpack-1-7-1-14.42781/
> 
> second suggest: (this suggestion if you don't understand it very well tell me and I will try to explain it further) I don't know if you played hypixel skyblock and you know what is the canvas room, my idea is a plugin like that:
> 
> you would have a spray which you fill with dyes, if you left click on the item it would open a menu where you could choose the public maps that people made or that were put pre-made and another one for maps that you made.
> 
> then there will be an area that the staff selected as canvas room where people can make their own pictures on a huge canvas and with a command could transform the image that made that user on a map and could even decide whether to put in the previous menu the image you made.
> 
> clearly it would be good to have placeholders so you can use them in other places or as a condition for anything.
> 
> links that I was guided by: https://hypixel-skyblock.fandom.com/wiki/Spray_Can https://hypixel-skyblock.fandom.com/wiki/Canvas_Room https://www.youtube.com/watch?v=5v33yhwPyLE https://youtu.be/9cKLWZW2Vbk

Hello and sorry for being so heavy but what happened in the end with the jetpack plugin suggestion that I had given you? in the end you will end up doing it or not? @ItsFlicker

**Comment by Zarkness2** [comment]
and another thing with the new update I can still create more than 1 texture pack?

**Comment by ItsFlicker** [comment]
Because not too many people need jetpack plugin and there have been some, it is suspended
if I continue it, I will make it an addon of SunSTCore

**Comment by ItsFlicker** [comment]
> and another thing with the new update I can still create more than 1 texture pack?

You can, I just change it from list to map so that it's more easy to read
you need to re-config after update

**Comment by Zarkness2** [comment]
> Because not too many people need jetpack plugin and there have been some, it is suspended if I continue it, I will make it an addon of SunSTCore

ok, and what plugin is SunSTCore? could you pass me the link of the plugin to see it and test it? besides what is the utility of this core?

**Comment by Zarkness2** [comment]
> > and another thing with the new update I can still create more than 1 texture pack?
> 
> You can, I just change it from list to map so that it's more easy to read you need to re-config after update

ok, thank you very much, for a moment I had thought you had removed that option

**Comment by ItsFlicker** [comment]
https://github.com/Sunshine-wzy/SunSTCore
It still wip, can't use

**Comment by Zarkness2** [comment]
ok, I will be waiting to see SunSTCore complete to see what is the utility or what it will be used for and also in case you get to take the jetpack plugin as an addon for it.
